SELECT DATABASE();


CREATE DATABASE ams;

CREATE TABLE IF NOT EXISTS `user`(
`id` INT PRIMARY KEY AUTO_INCREMENT COMMENT '用户id',
`username` VARCHAR(32) UNIQUE NOT NULL COMMENT '用户名',
`password` VARCHAR(128) NOT NULL COMMENT '用户密码',
`registerTime` BIGINT(20) DEFAULT NULL COMMENT '注册时间',
`updateTime` BIGINT(20) DEFAULT NULL COMMENT '更新时间',
`avatar` VARCHAR(256) DEFAULT NULL COMMENT '用户头像',
`phone` VARCHAR(32) DEFAULT NULL COMMENT '电话',
`gender` INT DEFAULT NULL COMMENT '性别',
`birth` BIGINT(20) DEFAULT NULL COMMENT '出生日期',
`location` VARCHAR(256) DEFAULT NULL COMMENT '所在地',
`registerAddress` VARCHAR(256) DEFAULT NULL COMMENT '注册地址信息',
`lastLoginAddress` VARCHAR(256) DEFAULT NULL COMMENT '最后登录地'
);